version: '3.7'
services:

  app:
    image: starlette_context
    container_name: starlette_context
    build: .
    command: ['scripts/test.sh']
    ports:
      - 8000:8000
    expose:
      - 8000
    restart: unless-stopped
    volumes:
      - .:/source/starlette_context
